# Generated by Django 5.0.5 on 2024-05-16 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='usuario',
            name='quarto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
