# Generated by Django 5.0.5 on 2024-05-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_usuario_data_usuario_endereco_usuario_idade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data',
            new_name='data_reserva',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='quarto',
            new_name='quarto_escolha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
